// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"di_sample/repo"
	"di_sample/service"
)

// Injectors from wire.go:

func InitializeUserService1() *service.UserService {
	iUserRepository := repo.NewUserRepo1()
	userService := service.NewUserService(iUserRepository)
	return userService
}

func InitializeUserService2() *service.UserService {
	iUserRepository := repo.NewUserRepo2()
	userService := service.NewUserService(iUserRepository)
	return userService
}

func InitializeUserServiceSingleton() *service.UserService {
	iUserRepository := repo.NewUserRepo1()
	userService := service.NewUserServiceSingleton(iUserRepository)
	return userService
}
