// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"di_sample/repo"
	"di_sample/service"
)

// Injectors from wire.go:

func InitializeUserService() *service.UserService {
	iUserRepository := repo.NewUserRepo()
	userService := service.NewUserServiceSingleton(iUserRepository)
	return userService
}
